import { ArrowLeft, ArrowRight } from "lucide-react";
import Link from "next/link";
import { RelayLogo } from "@/components/relay-logo";

export const metadata = { title: "Connecting your server — Relay" };

export default function ConnectionGuide() {
  return (
    <main className="guide-page">
      <header><Link href="/" aria-label="Relay home"><RelayLogo /></Link><Link className="button button--secondary" href="/"><ArrowLeft size={14} />Back to workspace</Link></header>
      <h1>A shorter path to your server.</h1>
      <p>Open Relay, enter your server address, TCP port, and RCON password, then connect. You can also paste a JSON configuration. There is no account or separate connection service to set up.</p>
      <div className="guide-flow" aria-label="Connection path: browser HTTPS to Relay, then TCP to CS2"><div><strong>Your browser</strong><small>Server details and commands</small></div><ArrowRight size={19} /><div><strong>This Relay installation</strong><small>Built-in TCP connection</small></div><ArrowRight size={19} /><div><strong>Your CS2 server</strong><small>Source RCON</small></div></div>
      <section><h2>Connect in a few steps</h2><ol><li>Enable Source RCON on your dedicated server and set a strong <code>rcon_password</code> in its configuration.</li><li>Allow the RCON <strong>TCP</strong> port through the server’s firewall. It is commonly <code>27015</code>; use the value supplied by your host.</li><li>Enter the address, port, and password in Relay. A successful connection reads the server status before opening the dashboard.</li></ol><p>The firewall must accept connections from the Relay host. Some game hosts provide a proprietary console instead of a Source RCON endpoint; ask the provider to enable TCP RCON in that case.</p></section>
      <section><h2>Paste your configuration</h2><pre>{'{\n  "name": "Friday night competitive",\n  "host": "cs2.example.com",\n  "port": 27015,\n  "password": "your-rcon-password"\n}'}</pre><p>The import also recognizes <code>ip</code>, <code>address</code>, <code>rcon_port</code>, <code>rconPort</code>, <code>rcon_password</code>, and <code>rconPassword</code>. Nested <code>rcon</code> or <code>server</code> objects, arrays, and Relay settings exports work too. Review the imported fields before connecting; an import never sends a command automatically.</p></section>
      <section><h2>Run Relay anywhere Node runs</h2><p>The UI and TCP connection handler are packaged together. Run them locally or on your own host:</p><pre>{'npm ci\nnpm run build\nnpm start'}</pre><p>Or use the included Docker configuration:</p><pre>{'docker compose up --build -d'}</pre><p>Open <code>http://localhost:3000</code>. The Docker port binds to loopback; for public access, put an HTTPS reverse proxy in front and set <code>RCON_PUBLIC_ORIGIN</code> to the site’s public URL. Use request and connection limits at the proxy for a public installation. Next.js documents this deployment in its <a href="https://nextjs.org/docs/app/guides/self-hosting">self-hosting guide</a>.</p><p>No installation key is required by default. If an existing installation still asks for one, its owner has set the optional <code>RCON_RELAY_SECRET</code>. Removing that environment variable and restarting restores keyless access.</p></section>
      <section><h2>Local and private servers</h2><p>A public Relay host cannot reach your home network. Run Relay on the same machine or network as the server. For a production installation, explicitly allow the private destination:</p><pre>{'RCON_ALLOW_PRIVATE=true\nRCON_ALLOWED_HOSTS=192.168.1.50'}</pre><p>Use the exact hostname or address entered in the connection form. Keep this installation on a trusted network or behind access control. Loopback inside a container refers to the container itself; use a reachable game-server address. Link-local metadata and reserved addresses remain blocked.</p></section>
      <section><h2>Where your password goes</h2><p>Your browser sends the password to this installation to authenticate with the game server. Relay uses it in memory and does not write it to a database. It stays out of browser storage unless you select “Remember password.” A remembered password is stored without encryption on this device.</p><p>HTTPS protects the browser-to-Relay hop. Source RCON sends the password in its TCP authentication packet, so the final server hop is unencrypted. Run Relay on a trusted host, preferably alongside the game server or over a private network. The <a href="https://www.mail-archive.com/hlds_apps@list.valvesoftware.com/msg00604.html">original Valve protocol specification</a> describes that packet format.</p></section>
      <section><h2>Why the browser still needs the app’s server</h2><p>Ordinary web pages cannot open arbitrary TCP sockets. Chrome’s <a href="https://developer.chrome.com/docs/iwa/direct-sockets">Direct Sockets API</a> is reserved for installed Isolated Web Apps. WebSocket, WebRTC, and WebTransport require their own compatible server protocols; a native CS2 RCON endpoint does not speak them.</p><p>Relay therefore uses its own Node runtime for TCP. It works without a separately deployed worker and supports common browsers. A purely static deployment cannot provide native RCON connectivity. Vercel’s <a href="https://vercel.com/docs/functions/runtimes/node-js">Node runtime</a> is an optional host, not a required dependency.</p></section>
      <section><h2>If a connection fails</h2><ul><li><strong>Connection refused:</strong> check RCON is enabled, the TCP port is correct, and the game server is running.</li><li><strong>Timeout:</strong> check routing, port forwarding, and the firewall allowance for the Relay host.</li><li><strong>Authentication failed:</strong> verify the password before trying again. Repeated bad passwords can cause the server to block the connection source.</li><li><strong>Private address blocked:</strong> use a Relay installation on that network with an explicit allowed host.</li><li><strong>Too many attempts:</strong> wait a minute before retrying. There are per-process and per-destination limits.</li></ul><p>Relay polls status and executes server commands. It cannot start a stopped game process, manage host files, or stream incoming chat through standard RCON alone.</p></section>
    </main>
  );
}
